package com.zoo.youshang.persistence;

import com.zoo.youshang.entity.MemberProfile;
import com.zoo.youshang.entity.MemberProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MemberProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    int countByExample(MemberProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    int deleteByExample(MemberProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    int insert(MemberProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    int insertSelective(MemberProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    List<MemberProfile> selectByExampleWithRowbounds(MemberProfileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    List<MemberProfile> selectByExample(MemberProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    MemberProfile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    int updateByExampleSelective(@Param("record") MemberProfile record, @Param("example") MemberProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    int updateByExample(@Param("record") MemberProfile record, @Param("example") MemberProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    int updateByPrimaryKeySelective(MemberProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    int updateByPrimaryKey(MemberProfile record);
}