package com.zoo.youshang.persistence;

import com.zoo.youshang.entity.TaskAcceptance;
import com.zoo.youshang.entity.TaskAcceptanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskAcceptanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    int countByExample(TaskAcceptanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    int deleteByExample(TaskAcceptanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    int insert(TaskAcceptance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    int insertSelective(TaskAcceptance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    List<TaskAcceptance> selectByExampleWithRowbounds(TaskAcceptanceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    List<TaskAcceptance> selectByExample(TaskAcceptanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    TaskAcceptance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    int updateByExampleSelective(@Param("record") TaskAcceptance record, @Param("example") TaskAcceptanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    int updateByExample(@Param("record") TaskAcceptance record, @Param("example") TaskAcceptanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    int updateByPrimaryKeySelective(TaskAcceptance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_acceptance
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    int updateByPrimaryKey(TaskAcceptance record);
}