package com.zoo.youshang.persistence;

import com.zoo.youshang.entity.TaskProfile;
import com.zoo.youshang.entity.TaskProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    int countByExample(TaskProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    int deleteByExample(TaskProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    int insert(TaskProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    int insertSelective(TaskProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    List<TaskProfile> selectByExampleWithRowbounds(TaskProfileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    List<TaskProfile> selectByExample(TaskProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    TaskProfile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    int updateByExampleSelective(@Param("record") TaskProfile record, @Param("example") TaskProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    int updateByExample(@Param("record") TaskProfile record, @Param("example") TaskProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    int updateByPrimaryKeySelective(TaskProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_profile
     *
     * @mbggenerated Wed Sep 04 09:59:09 CST 2013
     */
    int updateByPrimaryKey(TaskProfile record);
}