package com.zoo.youshang.entity;

import java.util.Date;

public class MemberProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile.id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile.username
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile.mobile
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile.weibo
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private String weibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile.score
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile.name
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile.last_login_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile.avatar_path
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private String avatarPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile.create_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile.update_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.id
     *
     * @return the value of member_profile.id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.id
     *
     * @param id the value for member_profile.id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.username
     *
     * @return the value of member_profile.username
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.username
     *
     * @param username the value for member_profile.username
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.mobile
     *
     * @return the value of member_profile.mobile
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.mobile
     *
     * @param mobile the value for member_profile.mobile
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.weibo
     *
     * @return the value of member_profile.weibo
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.weibo
     *
     * @param weibo the value for member_profile.weibo
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.score
     *
     * @return the value of member_profile.score
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.score
     *
     * @param score the value for member_profile.score
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.name
     *
     * @return the value of member_profile.name
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.name
     *
     * @param name the value for member_profile.name
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.last_login_time
     *
     * @return the value of member_profile.last_login_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.last_login_time
     *
     * @param lastLoginTime the value for member_profile.last_login_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.avatar_path
     *
     * @return the value of member_profile.avatar_path
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public String getAvatarPath() {
        return avatarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.avatar_path
     *
     * @param avatarPath the value for member_profile.avatar_path
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setAvatarPath(String avatarPath) {
        this.avatarPath = avatarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.create_time
     *
     * @return the value of member_profile.create_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.create_time
     *
     * @param createTime the value for member_profile.create_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.update_time
     *
     * @return the value of member_profile.update_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.update_time
     *
     * @param updateTime the value for member_profile.update_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}