package com.zoo.youshang.entity;

import java.util.Date;

public class TaskAcceptance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_acceptance.id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_acceptance.task_id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_acceptance.acceptor_id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Long acceptorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_acceptance.create_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_acceptance.update_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_acceptance.deleted
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_acceptance.id
     *
     * @return the value of task_acceptance.id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_acceptance.id
     *
     * @param id the value for task_acceptance.id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_acceptance.task_id
     *
     * @return the value of task_acceptance.task_id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_acceptance.task_id
     *
     * @param taskId the value for task_acceptance.task_id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_acceptance.acceptor_id
     *
     * @return the value of task_acceptance.acceptor_id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Long getAcceptorId() {
        return acceptorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_acceptance.acceptor_id
     *
     * @param acceptorId the value for task_acceptance.acceptor_id
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setAcceptorId(Long acceptorId) {
        this.acceptorId = acceptorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_acceptance.create_time
     *
     * @return the value of task_acceptance.create_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_acceptance.create_time
     *
     * @param createTime the value for task_acceptance.create_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_acceptance.update_time
     *
     * @return the value of task_acceptance.update_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_acceptance.update_time
     *
     * @param updateTime the value for task_acceptance.update_time
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_acceptance.deleted
     *
     * @return the value of task_acceptance.deleted
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_acceptance.deleted
     *
     * @param deleted the value for task_acceptance.deleted
     *
     * @mbggenerated Sun Sep 15 15:48:42 CST 2013
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}