package com.zoo.youshang.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TaskDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.id
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.sponsor_id
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private Long sponsorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.executor_id
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private Long executorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.reward
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private BigDecimal reward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.end_time
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.description
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.status
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.location
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.photo_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private String photoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.record_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private String recordPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.create_time
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.update_time
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.sponsor_name
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private String sponsorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.sponsor_mobile
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private String sponsorMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.sponsor_avatar_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private String sponsorAvatarPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.executor_name
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private String executorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.executor_mobile
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private String executorMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.executor_avatar_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    private String executorAvatarPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.id
     *
     * @return the value of task_detail.id
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.id
     *
     * @param id the value for task_detail.id
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.sponsor_id
     *
     * @return the value of task_detail.sponsor_id
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public Long getSponsorId() {
        return sponsorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.sponsor_id
     *
     * @param sponsorId the value for task_detail.sponsor_id
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setSponsorId(Long sponsorId) {
        this.sponsorId = sponsorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.executor_id
     *
     * @return the value of task_detail.executor_id
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public Long getExecutorId() {
        return executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.executor_id
     *
     * @param executorId the value for task_detail.executor_id
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setExecutorId(Long executorId) {
        this.executorId = executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.reward
     *
     * @return the value of task_detail.reward
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public BigDecimal getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.reward
     *
     * @param reward the value for task_detail.reward
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setReward(BigDecimal reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.end_time
     *
     * @return the value of task_detail.end_time
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.end_time
     *
     * @param endTime the value for task_detail.end_time
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.description
     *
     * @return the value of task_detail.description
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.description
     *
     * @param description the value for task_detail.description
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.status
     *
     * @return the value of task_detail.status
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.status
     *
     * @param status the value for task_detail.status
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.location
     *
     * @return the value of task_detail.location
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.location
     *
     * @param location the value for task_detail.location
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.photo_path
     *
     * @return the value of task_detail.photo_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.photo_path
     *
     * @param photoPath the value for task_detail.photo_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.record_path
     *
     * @return the value of task_detail.record_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getRecordPath() {
        return recordPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.record_path
     *
     * @param recordPath the value for task_detail.record_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setRecordPath(String recordPath) {
        this.recordPath = recordPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.create_time
     *
     * @return the value of task_detail.create_time
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.create_time
     *
     * @param createTime the value for task_detail.create_time
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.update_time
     *
     * @return the value of task_detail.update_time
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.update_time
     *
     * @param updateTime the value for task_detail.update_time
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.sponsor_name
     *
     * @return the value of task_detail.sponsor_name
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getSponsorName() {
        return sponsorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.sponsor_name
     *
     * @param sponsorName the value for task_detail.sponsor_name
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setSponsorName(String sponsorName) {
        this.sponsorName = sponsorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.sponsor_mobile
     *
     * @return the value of task_detail.sponsor_mobile
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getSponsorMobile() {
        return sponsorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.sponsor_mobile
     *
     * @param sponsorMobile the value for task_detail.sponsor_mobile
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setSponsorMobile(String sponsorMobile) {
        this.sponsorMobile = sponsorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.sponsor_avatar_path
     *
     * @return the value of task_detail.sponsor_avatar_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getSponsorAvatarPath() {
        return sponsorAvatarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.sponsor_avatar_path
     *
     * @param sponsorAvatarPath the value for task_detail.sponsor_avatar_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setSponsorAvatarPath(String sponsorAvatarPath) {
        this.sponsorAvatarPath = sponsorAvatarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.executor_name
     *
     * @return the value of task_detail.executor_name
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getExecutorName() {
        return executorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.executor_name
     *
     * @param executorName the value for task_detail.executor_name
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setExecutorName(String executorName) {
        this.executorName = executorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.executor_mobile
     *
     * @return the value of task_detail.executor_mobile
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getExecutorMobile() {
        return executorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.executor_mobile
     *
     * @param executorMobile the value for task_detail.executor_mobile
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setExecutorMobile(String executorMobile) {
        this.executorMobile = executorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.executor_avatar_path
     *
     * @return the value of task_detail.executor_avatar_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getExecutorAvatarPath() {
        return executorAvatarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.executor_avatar_path
     *
     * @param executorAvatarPath the value for task_detail.executor_avatar_path
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setExecutorAvatarPath(String executorAvatarPath) {
        this.executorAvatarPath = executorAvatarPath;
    }
}