package com.zoo.youshang.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TaskProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.id
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.sponsor_id
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private Long sponsorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.executor_id
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private Long executorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.reward
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private BigDecimal reward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.end_time
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.description
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.status
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.location
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.photo_path
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private String photoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.record_path
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private String recordPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.create_time
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_profile.update_time
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.id
     *
     * @return the value of task_profile.id
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.id
     *
     * @param id the value for task_profile.id
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.sponsor_id
     *
     * @return the value of task_profile.sponsor_id
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public Long getSponsorId() {
        return sponsorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.sponsor_id
     *
     * @param sponsorId the value for task_profile.sponsor_id
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setSponsorId(Long sponsorId) {
        this.sponsorId = sponsorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.executor_id
     *
     * @return the value of task_profile.executor_id
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public Long getExecutorId() {
        return executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.executor_id
     *
     * @param executorId the value for task_profile.executor_id
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setExecutorId(Long executorId) {
        this.executorId = executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.reward
     *
     * @return the value of task_profile.reward
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public BigDecimal getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.reward
     *
     * @param reward the value for task_profile.reward
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setReward(BigDecimal reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.end_time
     *
     * @return the value of task_profile.end_time
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.end_time
     *
     * @param endTime the value for task_profile.end_time
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.description
     *
     * @return the value of task_profile.description
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.description
     *
     * @param description the value for task_profile.description
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.status
     *
     * @return the value of task_profile.status
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.status
     *
     * @param status the value for task_profile.status
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.location
     *
     * @return the value of task_profile.location
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.location
     *
     * @param location the value for task_profile.location
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.photo_path
     *
     * @return the value of task_profile.photo_path
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.photo_path
     *
     * @param photoPath the value for task_profile.photo_path
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.record_path
     *
     * @return the value of task_profile.record_path
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public String getRecordPath() {
        return recordPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.record_path
     *
     * @param recordPath the value for task_profile.record_path
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setRecordPath(String recordPath) {
        this.recordPath = recordPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.create_time
     *
     * @return the value of task_profile.create_time
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.create_time
     *
     * @param createTime the value for task_profile.create_time
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_profile.update_time
     *
     * @return the value of task_profile.update_time
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_profile.update_time
     *
     * @param updateTime the value for task_profile.update_time
     *
     * @mbggenerated Mon Sep 09 11:58:23 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}