package com.zoo.youshang.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public TaskDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSponsorIdIsNull() {
            addCriterion("sponsor_id is null");
            return (Criteria) this;
        }

        public Criteria andSponsorIdIsNotNull() {
            addCriterion("sponsor_id is not null");
            return (Criteria) this;
        }

        public Criteria andSponsorIdEqualTo(Long value) {
            addCriterion("sponsor_id =", value, "sponsorId");
            return (Criteria) this;
        }

        public Criteria andSponsorIdNotEqualTo(Long value) {
            addCriterion("sponsor_id <>", value, "sponsorId");
            return (Criteria) this;
        }

        public Criteria andSponsorIdGreaterThan(Long value) {
            addCriterion("sponsor_id >", value, "sponsorId");
            return (Criteria) this;
        }

        public Criteria andSponsorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sponsor_id >=", value, "sponsorId");
            return (Criteria) this;
        }

        public Criteria andSponsorIdLessThan(Long value) {
            addCriterion("sponsor_id <", value, "sponsorId");
            return (Criteria) this;
        }

        public Criteria andSponsorIdLessThanOrEqualTo(Long value) {
            addCriterion("sponsor_id <=", value, "sponsorId");
            return (Criteria) this;
        }

        public Criteria andSponsorIdIn(List<Long> values) {
            addCriterion("sponsor_id in", values, "sponsorId");
            return (Criteria) this;
        }

        public Criteria andSponsorIdNotIn(List<Long> values) {
            addCriterion("sponsor_id not in", values, "sponsorId");
            return (Criteria) this;
        }

        public Criteria andSponsorIdBetween(Long value1, Long value2) {
            addCriterion("sponsor_id between", value1, value2, "sponsorId");
            return (Criteria) this;
        }

        public Criteria andSponsorIdNotBetween(Long value1, Long value2) {
            addCriterion("sponsor_id not between", value1, value2, "sponsorId");
            return (Criteria) this;
        }

        public Criteria andExecutorIdIsNull() {
            addCriterion("executor_id is null");
            return (Criteria) this;
        }

        public Criteria andExecutorIdIsNotNull() {
            addCriterion("executor_id is not null");
            return (Criteria) this;
        }

        public Criteria andExecutorIdEqualTo(Long value) {
            addCriterion("executor_id =", value, "executorId");
            return (Criteria) this;
        }

        public Criteria andExecutorIdNotEqualTo(Long value) {
            addCriterion("executor_id <>", value, "executorId");
            return (Criteria) this;
        }

        public Criteria andExecutorIdGreaterThan(Long value) {
            addCriterion("executor_id >", value, "executorId");
            return (Criteria) this;
        }

        public Criteria andExecutorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("executor_id >=", value, "executorId");
            return (Criteria) this;
        }

        public Criteria andExecutorIdLessThan(Long value) {
            addCriterion("executor_id <", value, "executorId");
            return (Criteria) this;
        }

        public Criteria andExecutorIdLessThanOrEqualTo(Long value) {
            addCriterion("executor_id <=", value, "executorId");
            return (Criteria) this;
        }

        public Criteria andExecutorIdIn(List<Long> values) {
            addCriterion("executor_id in", values, "executorId");
            return (Criteria) this;
        }

        public Criteria andExecutorIdNotIn(List<Long> values) {
            addCriterion("executor_id not in", values, "executorId");
            return (Criteria) this;
        }

        public Criteria andExecutorIdBetween(Long value1, Long value2) {
            addCriterion("executor_id between", value1, value2, "executorId");
            return (Criteria) this;
        }

        public Criteria andExecutorIdNotBetween(Long value1, Long value2) {
            addCriterion("executor_id not between", value1, value2, "executorId");
            return (Criteria) this;
        }

        public Criteria andRewardIsNull() {
            addCriterion("reward is null");
            return (Criteria) this;
        }

        public Criteria andRewardIsNotNull() {
            addCriterion("reward is not null");
            return (Criteria) this;
        }

        public Criteria andRewardEqualTo(BigDecimal value) {
            addCriterion("reward =", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotEqualTo(BigDecimal value) {
            addCriterion("reward <>", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardGreaterThan(BigDecimal value) {
            addCriterion("reward >", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("reward >=", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLessThan(BigDecimal value) {
            addCriterion("reward <", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLessThanOrEqualTo(BigDecimal value) {
            addCriterion("reward <=", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardIn(List<BigDecimal> values) {
            addCriterion("reward in", values, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotIn(List<BigDecimal> values) {
            addCriterion("reward not in", values, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reward between", value1, value2, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reward not between", value1, value2, "reward");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andPhotoPathIsNull() {
            addCriterion("photo_path is null");
            return (Criteria) this;
        }

        public Criteria andPhotoPathIsNotNull() {
            addCriterion("photo_path is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoPathEqualTo(String value) {
            addCriterion("photo_path =", value, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathNotEqualTo(String value) {
            addCriterion("photo_path <>", value, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathGreaterThan(String value) {
            addCriterion("photo_path >", value, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathGreaterThanOrEqualTo(String value) {
            addCriterion("photo_path >=", value, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathLessThan(String value) {
            addCriterion("photo_path <", value, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathLessThanOrEqualTo(String value) {
            addCriterion("photo_path <=", value, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathLike(String value) {
            addCriterion("photo_path like", value, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathNotLike(String value) {
            addCriterion("photo_path not like", value, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathIn(List<String> values) {
            addCriterion("photo_path in", values, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathNotIn(List<String> values) {
            addCriterion("photo_path not in", values, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathBetween(String value1, String value2) {
            addCriterion("photo_path between", value1, value2, "photoPath");
            return (Criteria) this;
        }

        public Criteria andPhotoPathNotBetween(String value1, String value2) {
            addCriterion("photo_path not between", value1, value2, "photoPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathIsNull() {
            addCriterion("record_path is null");
            return (Criteria) this;
        }

        public Criteria andRecordPathIsNotNull() {
            addCriterion("record_path is not null");
            return (Criteria) this;
        }

        public Criteria andRecordPathEqualTo(String value) {
            addCriterion("record_path =", value, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathNotEqualTo(String value) {
            addCriterion("record_path <>", value, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathGreaterThan(String value) {
            addCriterion("record_path >", value, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathGreaterThanOrEqualTo(String value) {
            addCriterion("record_path >=", value, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathLessThan(String value) {
            addCriterion("record_path <", value, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathLessThanOrEqualTo(String value) {
            addCriterion("record_path <=", value, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathLike(String value) {
            addCriterion("record_path like", value, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathNotLike(String value) {
            addCriterion("record_path not like", value, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathIn(List<String> values) {
            addCriterion("record_path in", values, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathNotIn(List<String> values) {
            addCriterion("record_path not in", values, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathBetween(String value1, String value2) {
            addCriterion("record_path between", value1, value2, "recordPath");
            return (Criteria) this;
        }

        public Criteria andRecordPathNotBetween(String value1, String value2) {
            addCriterion("record_path not between", value1, value2, "recordPath");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSponsorNameIsNull() {
            addCriterion("sponsor_name is null");
            return (Criteria) this;
        }

        public Criteria andSponsorNameIsNotNull() {
            addCriterion("sponsor_name is not null");
            return (Criteria) this;
        }

        public Criteria andSponsorNameEqualTo(String value) {
            addCriterion("sponsor_name =", value, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameNotEqualTo(String value) {
            addCriterion("sponsor_name <>", value, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameGreaterThan(String value) {
            addCriterion("sponsor_name >", value, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameGreaterThanOrEqualTo(String value) {
            addCriterion("sponsor_name >=", value, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameLessThan(String value) {
            addCriterion("sponsor_name <", value, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameLessThanOrEqualTo(String value) {
            addCriterion("sponsor_name <=", value, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameLike(String value) {
            addCriterion("sponsor_name like", value, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameNotLike(String value) {
            addCriterion("sponsor_name not like", value, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameIn(List<String> values) {
            addCriterion("sponsor_name in", values, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameNotIn(List<String> values) {
            addCriterion("sponsor_name not in", values, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameBetween(String value1, String value2) {
            addCriterion("sponsor_name between", value1, value2, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorNameNotBetween(String value1, String value2) {
            addCriterion("sponsor_name not between", value1, value2, "sponsorName");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileIsNull() {
            addCriterion("sponsor_mobile is null");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileIsNotNull() {
            addCriterion("sponsor_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileEqualTo(String value) {
            addCriterion("sponsor_mobile =", value, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileNotEqualTo(String value) {
            addCriterion("sponsor_mobile <>", value, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileGreaterThan(String value) {
            addCriterion("sponsor_mobile >", value, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileGreaterThanOrEqualTo(String value) {
            addCriterion("sponsor_mobile >=", value, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileLessThan(String value) {
            addCriterion("sponsor_mobile <", value, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileLessThanOrEqualTo(String value) {
            addCriterion("sponsor_mobile <=", value, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileLike(String value) {
            addCriterion("sponsor_mobile like", value, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileNotLike(String value) {
            addCriterion("sponsor_mobile not like", value, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileIn(List<String> values) {
            addCriterion("sponsor_mobile in", values, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileNotIn(List<String> values) {
            addCriterion("sponsor_mobile not in", values, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileBetween(String value1, String value2) {
            addCriterion("sponsor_mobile between", value1, value2, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorMobileNotBetween(String value1, String value2) {
            addCriterion("sponsor_mobile not between", value1, value2, "sponsorMobile");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathIsNull() {
            addCriterion("sponsor_avatar_path is null");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathIsNotNull() {
            addCriterion("sponsor_avatar_path is not null");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathEqualTo(String value) {
            addCriterion("sponsor_avatar_path =", value, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathNotEqualTo(String value) {
            addCriterion("sponsor_avatar_path <>", value, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathGreaterThan(String value) {
            addCriterion("sponsor_avatar_path >", value, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathGreaterThanOrEqualTo(String value) {
            addCriterion("sponsor_avatar_path >=", value, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathLessThan(String value) {
            addCriterion("sponsor_avatar_path <", value, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathLessThanOrEqualTo(String value) {
            addCriterion("sponsor_avatar_path <=", value, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathLike(String value) {
            addCriterion("sponsor_avatar_path like", value, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathNotLike(String value) {
            addCriterion("sponsor_avatar_path not like", value, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathIn(List<String> values) {
            addCriterion("sponsor_avatar_path in", values, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathNotIn(List<String> values) {
            addCriterion("sponsor_avatar_path not in", values, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathBetween(String value1, String value2) {
            addCriterion("sponsor_avatar_path between", value1, value2, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andSponsorAvatarPathNotBetween(String value1, String value2) {
            addCriterion("sponsor_avatar_path not between", value1, value2, "sponsorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorNameIsNull() {
            addCriterion("executor_name is null");
            return (Criteria) this;
        }

        public Criteria andExecutorNameIsNotNull() {
            addCriterion("executor_name is not null");
            return (Criteria) this;
        }

        public Criteria andExecutorNameEqualTo(String value) {
            addCriterion("executor_name =", value, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameNotEqualTo(String value) {
            addCriterion("executor_name <>", value, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameGreaterThan(String value) {
            addCriterion("executor_name >", value, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameGreaterThanOrEqualTo(String value) {
            addCriterion("executor_name >=", value, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameLessThan(String value) {
            addCriterion("executor_name <", value, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameLessThanOrEqualTo(String value) {
            addCriterion("executor_name <=", value, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameLike(String value) {
            addCriterion("executor_name like", value, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameNotLike(String value) {
            addCriterion("executor_name not like", value, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameIn(List<String> values) {
            addCriterion("executor_name in", values, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameNotIn(List<String> values) {
            addCriterion("executor_name not in", values, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameBetween(String value1, String value2) {
            addCriterion("executor_name between", value1, value2, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorNameNotBetween(String value1, String value2) {
            addCriterion("executor_name not between", value1, value2, "executorName");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileIsNull() {
            addCriterion("executor_mobile is null");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileIsNotNull() {
            addCriterion("executor_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileEqualTo(String value) {
            addCriterion("executor_mobile =", value, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileNotEqualTo(String value) {
            addCriterion("executor_mobile <>", value, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileGreaterThan(String value) {
            addCriterion("executor_mobile >", value, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileGreaterThanOrEqualTo(String value) {
            addCriterion("executor_mobile >=", value, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileLessThan(String value) {
            addCriterion("executor_mobile <", value, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileLessThanOrEqualTo(String value) {
            addCriterion("executor_mobile <=", value, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileLike(String value) {
            addCriterion("executor_mobile like", value, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileNotLike(String value) {
            addCriterion("executor_mobile not like", value, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileIn(List<String> values) {
            addCriterion("executor_mobile in", values, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileNotIn(List<String> values) {
            addCriterion("executor_mobile not in", values, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileBetween(String value1, String value2) {
            addCriterion("executor_mobile between", value1, value2, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorMobileNotBetween(String value1, String value2) {
            addCriterion("executor_mobile not between", value1, value2, "executorMobile");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathIsNull() {
            addCriterion("executor_avatar_path is null");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathIsNotNull() {
            addCriterion("executor_avatar_path is not null");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathEqualTo(String value) {
            addCriterion("executor_avatar_path =", value, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathNotEqualTo(String value) {
            addCriterion("executor_avatar_path <>", value, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathGreaterThan(String value) {
            addCriterion("executor_avatar_path >", value, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathGreaterThanOrEqualTo(String value) {
            addCriterion("executor_avatar_path >=", value, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathLessThan(String value) {
            addCriterion("executor_avatar_path <", value, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathLessThanOrEqualTo(String value) {
            addCriterion("executor_avatar_path <=", value, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathLike(String value) {
            addCriterion("executor_avatar_path like", value, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathNotLike(String value) {
            addCriterion("executor_avatar_path not like", value, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathIn(List<String> values) {
            addCriterion("executor_avatar_path in", values, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathNotIn(List<String> values) {
            addCriterion("executor_avatar_path not in", values, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathBetween(String value1, String value2) {
            addCriterion("executor_avatar_path between", value1, value2, "executorAvatarPath");
            return (Criteria) this;
        }

        public Criteria andExecutorAvatarPathNotBetween(String value1, String value2) {
            addCriterion("executor_avatar_path not between", value1, value2, "executorAvatarPath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_detail
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 15 16:10:34 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_detail
     *
     * @mbggenerated Sun Sep 15 16:10:34 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}